# Generated by Django 4.1.1 on 2022-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("fb", "facebook"),
                    ("google", "google"),
                    ("twitter", "twitter"),
                    ("email", "email"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
