# Generated by Django 4.1.1 on 2022-09-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("fb", "facebook"), ("email", "email")],
                default="email",
                max_length=20,
            ),
        ),
    ]
