# Generated by Django 4.1.1 on 2022-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_alter_chat_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
