# Generated by Django 4.1.1 on 2022-10-13 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_alter_chat_id_alter_message_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_sent",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
