# Generated by Django 4.1.1 on 2022-10-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["id"]},
        ),
    ]
